### PR TITLE
fix typo

### PR DESCRIPTION
**Pull request by MrSkinny**

### CODE REVIEW

**Comment by tomatau** [comment]
I RRREALLY want some CI on this for merging PRs... Would it add too much confusion for students if the repo contained circle or travis files?

**Comment by MrSkinny** [comment]
I don't think so -- the curriculum could have a note in the early checkpoints that summarizes what the file is for, but that it can be safely ignored at this time.

The bigger problem is that won't some branches intentionally have failing tests as part of the learning path from following the curric directions? And some checkpoints/mid-way solutions won't have tests.  Unless the idea is for the CI tests to be specific to the curric's intention and different from any "in-exercise" tests?

**Comment by tomatau** [comment]
I think most branches and their corresponding checkpoint code were developed using a TDD style approach so they should have only passing tests.

Ensuring all of the branches get updated when we make a PR is also an important step for these repos as I think inconsistent branches that build on each other will be very confusing for students.

**Comment by MrSkinny** [comment]
Good point. I've updated the subsequent branches as well.

**Pull request merged**
